name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test last version of Linux v2.6
        id: linux-2-6-39
        uses: ./
        with:
          repo: https://github.com/torvalds/linux.git
          tag: '^v2\.6\.[0-9]+$'

      - name: Test last RC version of Linux v2.6.39
        id: linux-2-6-39-rc7
        uses: ./
        with:
          repo: https://github.com/torvalds/linux.git
          tag: '^v2\.6\.[0-9]\-rc[0-9]+$'

      - name: Test tags
        run: |
          ./test.sh "${{ steps.linux-2-6-39.outputs.tag }}" = "v2.6.39" 
          ./test.sh "${{ steps.linux-2-6-39-rc7.outputs.tag }}" = "v2.6.39-rc7" 
